change type from String to int and fix some typo
tdM05/FullStackChef pull request #24
Opened 2024-11-09 23:33 UTC by jasmine-artsci

change type from String to int for recipeId, and fix some typo

2024-11-09 23:47 UTC, miminmoons approved these changes

2024-11-10 00:40 UTC, miminmoons requested changes
In method DisplayRecipeOutputData, nutritionalInfo is of type NutritionalInfo (line 22), but on line 19 it is defined as NutritionalInfoOutput

2024-11-10 01:00 UTC, tdM05 approved these changes

2024-11-10 01:37 UTC, miminmoons approved these changes

2024-11-10 04:19 UTC, closed without merging